version: '3'
services:
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"  
    healthcheck:
        test: ["CMD", "sh", "-c", "curl -f http://localhost:9000/api/system/status | grep -q '\"status\":\"UP\"'"]
        interval: 30s
        start_period: 60s
        retries: 5
        timeout: 10s
          # token-fetch:
          # image: alpine:latest
          #volumes:
          #- token-volume:/shared
          #- ./get_token.sh:/get_token.sh.
          #command: sh /get-token.sh
  sonar-scanner:
    # image: sonarsource/sonar-scanner-cli
    #
    build: 
      context: .
      dockerfile: Dockerfile.sonar
    environment:
      SONAR_HOST_URL: http://sonarqube:9000
      SONAR_PROJECT_KEY: revamped-website
    volumes:
      - ..:/usr/src
    depends_on:
      sonarqube:
        condition: service_healthy


# app2 can access app1 via: http://app1:9000
