export const projectsData = [
    {
        id: 19,
        title: "Next JS CI/CD pipeline with load testing and integration testing",
        technologies: "Gitlab CI/CD • Docker • Docker Compose • Shell • React • NextJS ",
        description: "Creating a CI/CD pipeline with load testing and integration testing",
        gradient: "bg-gradient-to-br from-white to-white",
        backgroundImage: "/projects/gitlab.png",
        overlay: "bg-black bg-opacity-35",
        githubUrl: "https://gitlab.com/thaileaf-group/RevampedWebsite",
        blogUrl: "https://blog.lethaison.com/creating-a-next-js-ci-cd-pipeline-with-load-testing-and-end-to-end-automated-integration-testing/",
        liveUrl: "https://gitlab.com/thaileaf-group/RevampedWebsite/-/pipelines",
    },
    {
        id: 18,
        title: "Terraforming Ghost Blog into a Single EC2 instance",
        technologies: "Terraform • AWS EC2 • Linux • Ubuntu • Shell • DNS ",
        description: "Deploying Ghost blog platform on a single t2.micro EC2 instance with CloudFront CDN within free tier limits",
        gradient: "bg-gradient-to-br from-violet-600 to-purple-700",
        backgroundImage: "/projects/ghost.png",
        overlay: "bg-black bg-opacity-35",
        githubUrl: "https://github.com/Thaileaf/AWSGhostTerraform?tab=readme-ov-file",
        blogUrl: "https://blog.lethaison.com/fitting-ghost-blog-into-a-micro-aws-ec2-server/",
    },
    {
        id: 13,
        title: "NYU K12 STEM Center Website",
        technologies: "React • Next.js • AWS • Sanity CMS • Javascript • Typescript ",
        description: "Official website for NYU's K12 Center for STEM Education, handling 30,000+ monthly visitors with modern cloud infrastructure and optimized performance",
        gradient: "bg-gradient-to-br from-violet-600 to-purple-700",
        backgroundImage: "/projects/k12.png",
        overlay: "bg-black bg-opacity-35",
        githubUrl: "https://github.com/Thaileaf/NYUK12Website",
        liveUrl: "https://k12stem.engineering.nyu.edu",
    },
    {
        id: 14,
        title: "Minecraft Server with CloudWatch Monitoring",
        technologies: "AWS Lightsail • CloudWatch • Lambda • EC2 • VPC",
        description: "Create a Minecraft Java Edition server with real-time player activity monitoring using CloudWatch and learn server management with monitoring best practices",
        gradient: "bg-gradient-to-br from-green-500 to-emerald-600",
        backgroundImage: "/projects/cloudwatch.png",
        overlay: "bg-black bg-opacity-30",
        githubUrl: "https://github.com/Thaileaf/AWS-Projects/tree/main/Proj-1-Minecraft-Server",
    },
    {
        id: 15,
        title: "Jellyfin Netflix-Like Media Server",
        technologies: "EC2 • VPC • ALB • S3 • EBS • IAM",
        description: "Build a secure, scalable media server using Jellyfin with HTTPS access and S3 storage integration to create your own streaming platform",
        gradient: "bg-gradient-to-br from-red-500 to-pink-600",
        backgroundImage: "/projects/stream.png",
        overlay: "bg-black bg-opacity-35",
        githubUrl: "https://github.com/Thaileaf/AWS-Projects/tree/main/Proj-2-Netflix-Like-Media-Server",
    },
    {
        id: 16,
        title: "Email Masking Service",
        technologies: "Route 53 • SES • Lambda • DynamoDB • S3",
        description: "Create a serverless email masking service that protects your real email address while allowing you to receive messages securely",
        gradient: "bg-gradient-to-br from-blue-500 to-indigo-600",
        backgroundImage: "/projects/mailmask.png",
        overlay: "bg-black bg-opacity-25",
        githubUrl: "https://github.com/Thaileaf/AWS-Projects/tree/main/Proj-3-Mail-Mask",
    },
    {
        id: 17,
        title: "Portfolio Website (5-Part Series)",
        technologies: "S3 • IAM • VPC • EC2 • RDS • API Gateway • Lambda • CloudFront",
        description: "Deploy a complete portfolio website progressing from static hosting to a full-stack serverless application with global content delivery",
        gradient: "bg-gradient-to-br from-purple-500 to-violet-600",
        backgroundImage: "/projects/portfolio.jpg",
        overlay: "bg-black bg-opacity-30",
        githubUrl: "https://github.com/Thaileaf/AWS-Projects/tree/main/Proj-4-Porfolio",
    },
    {
        id: 11,
        title: "TAJ: Endoscopic Surgery Platform",
        technologies: "YOLOv5 • Computer Vision • Medical AI • Python",
        description: "A platform integrating tumor detection and depth perception for endoscopic surgery with 95.5% precision using YOLOv5 and custom depth estimation algorithms",
        gradient: "bg-gradient-to-br from-red-500 to-pink-600",
        backgroundImage: "/projects/taj.png",
        overlay: "bg-black bg-opacity-30",
        githubUrl: "https://github.com/Thaileaf/EndoscopicYolo",
    },
    // {
    //     id: 12,
    //     title: "AWS Learning Projects Collection",
    //     technologies: "AWS • Cloud Infrastructure • DevOps • Educational Content",
    //     description: "A comprehensive collection of hands-on AWS tutorials for K12 STEM education, including Minecraft servers, media streaming, and serverless applications",
    //     gradient: "bg-gradient-to-br from-orange-500 to-amber-600",
    //     backgroundImage: "/projects/aws-projects.png",
    //     overlay: "bg-black bg-opacity-25",
    //     githubUrl: "https://github.com/Thaileaf/AWS-Projects",
    // },
    {
        id: 1,
        title: "Google Quick Draw Clone",
        technologies: "Machine Learning • SVMs • Neural Networks • Canvas API",
        description: "An application that uses custom built models, such as SVMs and Neural Networks, to guess user drawings",
        gradient: "bg-gradient-to-br from-blue-400 to-purple-500",
        backgroundImage: "/projects/quickdraw.png",
        overlay: "bg-black bg-opacity-20",
        githubUrl: "https://github.com/BerryLiu2002/MLProject",
        // liveUrl: "https://quick-draw-clone.vercel.app",
    },
    {
        id: 2,
        title: "Airline Ticket Booking Service",
        technologies: "Full Stack • Database Design • CRUD",
        description: "An online flight booking service that facilitates the purchase of airline tickets",
        gradient: "bg-gradient-to-br from-sky-400 to-blue-600",
        backgroundImage: "/projects/booking.jpg",
        overlay: "bg-blue bg-opacity-10",
        githubUrl: "https://github.com/Thaileaf/DeytabaseAirlines",
        // liveUrl: "https://airline-booking-tl.herokuapp.com",
    },
    // {
    //     id: 3,
    //     title: "Web Development Playground",
    //     technologies: "HTML • CSS • JavaScript • Responsive Design",
    //     description: "Series of web pages developed in the pursuit of html/css/javascript knowledge",
    //     gradient: "bg-gradient-to-br from-orange-400 to-red-500",
    //     backgroundImage: "/images/projects/web-playground.png",
    //     overlay: "bg-black bg-opacity-30",
    //     githubUrl: "https://github.com/thaisonle/web-dev-playground",
    //     liveUrl: "https://thaisonle.github.io/web-playground",
    // },
    {
        id: 4,
        title: "Perlin Noise Flow Field Simulator",
        technologies: "P5.js • Javascript • Interactive Design",
        description: "An interactive canvas using P5.js to simulate particle physics through a perlin noise flow field",
        gradient: "bg-gradient-to-br from-green-400 to-cyan-500",
        backgroundImage: "/projects/flowfield.gif",
        overlay: "bg-black bg-opacity-25",
        githubUrl: "https://github.com/Thaileaf/Thaileaf.github.io/tree/main/P5",
        liveUrl: "https://thaileaf.github.io/P5/index.html",
    },
    {
        id: 5,
        title: "NYU Augmented Library Mobile App",
        technologies: "React Native • Mobile Development • AR Technology • UX Design",
        description: "A mobile application designed at NYU with the aim of providing NYU Dibner library users ease of access to all services through the use of AR technology",
        gradient: "bg-gradient-to-br from-purple-500 to-indigo-600",
        backgroundImage: "/projects/vip.png",
        overlay: "bg-black bg-opacity-40",
        githubUrl: "https://github.com/Thaileaf/NYU-Library-Frontend",
    },
    {
        id: 6,
        title: "Machine Code Assembler & Processor Simulator",
        technologies: "System Programming • Assembly Language • Computer Architecture",
        description: "An assembler that parses instructions from a rudimentary assembly language, transposing it into machine code, plus a processor simulator based off x86 architecture",
        gradient: "bg-gradient-to-br from-gray-600 to-gray-800",
        backgroundImage: "/projects/asm.png",
        overlay: "bg-black bg-opacity-50",
        githubUrl: "https://github.com/Thaileaf/MachineCodeCompilerSimulator",
    },
    {
        id: 7,
        title: "Discord Bot Animal Racer",
        technologies: "Discord API • Node.js • Game Logic • Real-time Events",
        description: "A small discord bot using the Discord API to create a small racing game with animal emojis between multiple users",
        gradient: "bg-gradient-to-br from-indigo-400 to-purple-600",
        backgroundImage: "/projects/discordbot.png",
        overlay: "bg-black bg-opacity-30",
        githubUrl: "https://github.com/Thaileaf/DiscordProjectFirst/blob/master/cogs/AnimalRace.py",
    },
    {
        id: 8,
        title: "Spotify Manager",
        technologies: "Python • Spotify API • Data Management • Backup Systems",
        description: "A desktop application that allows Spotify users to create back ups of playlist and song information through the spotify API",
        gradient: "bg-gradient-to-br from-green-500 to-emerald-600",
        backgroundImage: "/projects/spotify.png",
        overlay: "bg-black bg-opacity-25",
        githubUrl: "https://github.com/Thaileaf/SpotifyManager",
    },
    {
        id: 9,
        title: "Python Hot Reloading Module",
        technologies: "Python • Module Development • File System Monitoring",
        description: "A python module designed to hot reload python files, similar to javascript hot reloading. This allows changes to be made the program while it is running",
        gradient: "bg-gradient-to-br from-yellow-400 to-orange-500",
        backgroundImage: "/projects/hot-reload.png",
        overlay: "bg-black bg-opacity-30",
        githubUrl: "https://github.com/Thaileaf/Python-Hot-Reloader",
    },
    {
        id: 10,
        title: "Automation Scripts Collection",
        technologies: "Bash • PowerShell • System Administration • Automation",
        description: "A handful of bash and powershell scripts that provide use in work and projects",
        gradient: "bg-gradient-to-br from-slate-500 to-slate-700",
        backgroundImage: "/images/projects/automation-scripts.png",
        overlay: "bg-black bg-opacity-45",
        githubUrl: "https://github.com/Thaileaf/scripts",
    }
];