export const projectsData = [
    {
        id: 1,
        title: "Google Quick Draw Clone",
        technologies: "Machine Learning • SVMs • Neural Networks • Canvas API",
        description: "An application that uses custom built models, such as SVMs and Neural Networks, to guess user drawings",
        gradient: "bg-gradient-to-br from-blue-400 to-purple-500",
        backgroundImage: "/projects/quickdraw.png",
        overlay: "bg-black bg-opacity-20",
        githubUrl: "https://github.com/BerryLiu2002/MLProject",
        // liveUrl: "https://quick-draw-clone.vercel.app",
    },
    {
        id: 2,
        title: "Airline Ticket Booking Service",
        technologies: "Full Stack • Database Design • CRUD",
        description: "An online flight booking service that facilitates the purchase of airline tickets",
        gradient: "bg-gradient-to-br from-sky-400 to-blue-600",
        backgroundImage: "/projects/booking.jpg",
        overlay: "bg-blue bg-opacity-10",
        githubUrl: "https://github.com/Thaileaf/DeytabaseAirlines",
        // liveUrl: "https://airline-booking-tl.herokuapp.com",
    },
    // {
    //     id: 3,
    //     title: "Web Development Playground",
    //     technologies: "HTML • CSS • JavaScript • Responsive Design",
    //     description: "Series of web pages developed in the pursuit of html/css/javascript knowledge",
    //     gradient: "bg-gradient-to-br from-orange-400 to-red-500",
    //     backgroundImage: "/images/projects/web-playground.png",
    //     overlay: "bg-black bg-opacity-30",
    //     githubUrl: "https://github.com/thaisonle/web-dev-playground",
    //     liveUrl: "https://thaisonle.github.io/web-playground",
    // },
    {
        id: 4,
        title: "Perlin Noise Flow Field Simulator",
        technologies: "P5.js • Javascript • Interactive Design",
        description: "An interactive canvas using P5.js to simulate particle physics through a perlin noise flow field",
        gradient: "bg-gradient-to-br from-green-400 to-cyan-500",
        backgroundImage: "/projects/flowfield.gif",
        overlay: "bg-black bg-opacity-25",
        githubUrl: "https://github.com/Thaileaf/Thaileaf.github.io/tree/main/P5",
        liveUrl: "https://thaileaf.github.io/P5/index.html",
    },
    {
        id: 5,
        title: "NYU Augmented Library Mobile App",
        technologies: "React Native • Mobile Development • AR Technology • UX Design",
        description: "A mobile application designed at NYU with the aim of providing NYU Dibner library users ease of access to all services through the use of AR technology",
        gradient: "bg-gradient-to-br from-purple-500 to-indigo-600",
        backgroundImage: "/projects/vip.png",
        overlay: "bg-black bg-opacity-40",
        githubUrl: "https://github.com/Thaileaf/NYU-Library-Frontend",
    },
    {
        id: 6,
        title: "Machine Code Assembler & Processor Simulator",
        technologies: "System Programming • Assembly Language • Computer Architecture",
        description: "An assembler that parses instructions from a rudimentary assembly language, transposing it into machine code, plus a processor simulator based off x86 architecture",
        gradient: "bg-gradient-to-br from-gray-600 to-gray-800",
        backgroundImage: "/projects/asm.png",
        overlay: "bg-black bg-opacity-50",
        githubUrl: "https://github.com/Thaileaf/MachineCodeCompilerSimulator",
    },
    {
        id: 7,
        title: "Discord Bot Animal Racer",
        technologies: "Discord API • Node.js • Game Logic • Real-time Events",
        description: "A small discord bot using the Discord API to create a small racing game with animal emojis between multiple users",
        gradient: "bg-gradient-to-br from-indigo-400 to-purple-600",
        backgroundImage: "/projects/discordbot.png",
        overlay: "bg-black bg-opacity-30",
        githubUrl: "https://github.com/Thaileaf/DiscordProjectFirst/blob/master/cogs/AnimalRace.py",
    },
    {
        id: 8,
        title: "Spotify Manager",
        technologies: "Python • Spotify API • Data Management • Backup Systems",
        description: "A desktop application that allows Spotify users to create back ups of playlist and song information through the spotify API",
        gradient: "bg-gradient-to-br from-green-500 to-emerald-600",
        backgroundImage: "/projects/spotify.png",
        overlay: "bg-black bg-opacity-25",
        githubUrl: "https://github.com/Thaileaf/SpotifyManager",
    },
    {
        id: 9,
        title: "Python Hot Reloading Module",
        technologies: "Python • Module Development • File System Monitoring",
        description: "A python module designed to hot reload python files, similar to javascript hot reloading. This allows changes to be made the program while it is running",
        gradient: "bg-gradient-to-br from-yellow-400 to-orange-500",
        backgroundImage: "/projects/hot-reload.png",
        overlay: "bg-black bg-opacity-30",
        githubUrl: "https://github.com/Thaileaf/Python-Hot-Reloader",
    },
    {
        id: 10,
        title: "Automation Scripts Collection",
        technologies: "Bash • PowerShell • System Administration • Automation",
        description: "A handful of bash and powershell scripts that provide use in work and projects",
        gradient: "bg-gradient-to-br from-slate-500 to-slate-700",
        backgroundImage: "/images/projects/automation-scripts.png",
        overlay: "bg-black bg-opacity-45",
        githubUrl: "https://github.com/Thaileaf/scripts",
    }
];